# Generated by Django 5.1.5 on 2025-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('mecanica', 'Mecanica'), ('automata', 'Automata')], default='mecanica', max_length=10),
        ),
    ]
