# Generated by Django 5.1.5 on 2025-01-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('plugin_hybrid', 'Plug-in Hybrid'), ('hybrid', 'Hybrid'), ('benzine', 'Benzine'), ('electric', 'Electric')], default='diesel', max_length=16),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
