# Generated by Django 4.2.5 on 2025-01-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_car_fuel_type_car_mileage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-year']},
        ),
    ]
